### ISSUE TITLE
Volume notification displays whenever some media starts or stops playing

### ISSUE THREAD

**Issue by alba4k** [REALERvolker1/volbright#1]
This happens whenever any sound is played, e.g. using `echo \a` in a terminal. 

Actually, this happens even when you go forward or backwards in a youtube video, or even press `i` to minimize it

This is caused by any of these actions triggering a response in `pactl subscribe`

**Comment by REALERvolker1** [comment]
I will look at fixing it, or (hopefully I don't have to do this) making it so you trigger the notification with a keybind.

**Comment by alba4k** [comment]
that could work if we only consider the volume chaning via the keys, but you can also slide it up or down in many DEs, or in a WM (like in my setup) by scrolling on a module in polybar

**Comment by REALERvolker1** [comment]
Just fixed it. It was easier than I expected. All I had to do was keep state.

I have been annoyed with it displaying the popup too, and I am kind of surprised I didn't do this earlier.

Also threw in an instance checker because `$exec volbright.sh --brightness --keyboard` is much more elegant than `$exec "killall volbright.sh; volbright.sh --brightness --keyboard"`
